# Файл docker-compose должен начинаться с тега версии.
# Мы используем "3" так как это - самая свежая версия на момент написания этого кода.

version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:8080

