version: '3.8'

services:
  python-echo:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    hostname: python-server
    ports:
      - "5000:5000"
    environment:
      TZ: "Europe/Moscow"
    networks:
      - app-network


  nginx:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      TZ: "Europe/Moscow"
    depends_on:
      - python-echo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
