version: '3.8'

services:
  python-echo:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    hostname: echo-server
    ports:
      - "5000:5000"
    environment:
      TZ: "Europe/Moscow"
  nginx:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      TZ: "Europe/Moscow"
